spring:
  profiles:
    active: dev

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  config-location: classpath:conf/mybatis-config.xml
  # 全局主键策略
  global-config:
    db-config:
      id-type: id_worker  #默认
  type-aliases-package: com.starix.chat.entity
